
namespace cafe
{
    partial class ThongTin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ThongTin));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton3 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton4 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton5 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton6 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton7 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bt_thoat = new System.Windows.Forms.Button();
            this.txt_mk = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_chucvu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_tk = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_sdt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_gioitinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ten = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ma = new Bunifu.UI.WinForms.BunifuTextBox();
            this.hanh = new System.Windows.Forms.PictureBox();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.hanh)).BeginInit();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tableLayoutPanel1.BackgroundImage")));
            this.tableLayoutPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tableLayoutPanel1.ColumnCount = 6;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 21.25786F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.33962F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10.18868F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.08176F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 21.14428F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 176F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton1, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton2, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton3, 1, 3);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton4, 1, 4);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton5, 1, 5);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton6, 1, 6);
            this.tableLayoutPanel1.Controls.Add(this.bunifuImageButton7, 1, 7);
            this.tableLayoutPanel1.Controls.Add(this.bt_thoat, 3, 8);
            this.tableLayoutPanel1.Controls.Add(this.txt_mk, 3, 7);
            this.tableLayoutPanel1.Controls.Add(this.txt_chucvu, 3, 5);
            this.tableLayoutPanel1.Controls.Add(this.txt_tk, 3, 6);
            this.tableLayoutPanel1.Controls.Add(this.txt_sdt, 3, 4);
            this.tableLayoutPanel1.Controls.Add(this.txt_gioitinh, 3, 3);
            this.tableLayoutPanel1.Controls.Add(this.txt_ten, 3, 2);
            this.tableLayoutPanel1.Controls.Add(this.txt_ma, 3, 1);
            this.tableLayoutPanel1.Controls.Add(this.hanh, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 9;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 27.73224F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.426229F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.699453F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.103825F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8.879782F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8.196721F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.426229F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9.016394F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10.2459F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(826, 732);
            this.tableLayoutPanel1.TabIndex = 67;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.BackgroundImage")));
            this.bunifuImageButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = null;
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 40;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(47, 23);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(87, 63);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(141, 206);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(87, 63);
            this.bunifuImageButton1.TabIndex = 71;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 40;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.BackgroundImage")));
            this.bunifuImageButton2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = null;
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 40;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(47, 23);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(87, 63);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(141, 275);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(87, 63);
            this.bunifuImageButton2.TabIndex = 72;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 40;
            this.bunifuImageButton2.ZoomSpeed = 10;
            // 
            // bunifuImageButton3
            // 
            this.bunifuImageButton3.ActiveImage = null;
            this.bunifuImageButton3.AllowAnimations = true;
            this.bunifuImageButton3.AllowBuffering = false;
            this.bunifuImageButton3.AllowToggling = false;
            this.bunifuImageButton3.AllowZooming = true;
            this.bunifuImageButton3.AllowZoomingOnFocus = false;
            this.bunifuImageButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton3.BackgroundImage")));
            this.bunifuImageButton3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton3.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton3.ErrorImage")));
            this.bunifuImageButton3.FadeWhenInactive = false;
            this.bunifuImageButton3.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton3.Image = null;
            this.bunifuImageButton3.ImageActive = null;
            this.bunifuImageButton3.ImageLocation = null;
            this.bunifuImageButton3.ImageMargin = 40;
            this.bunifuImageButton3.ImageSize = new System.Drawing.Size(47, 6);
            this.bunifuImageButton3.ImageZoomSize = new System.Drawing.Size(87, 46);
            this.bunifuImageButton3.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton3.InitialImage")));
            this.bunifuImageButton3.Location = new System.Drawing.Point(141, 346);
            this.bunifuImageButton3.Name = "bunifuImageButton3";
            this.bunifuImageButton3.Rotation = 0;
            this.bunifuImageButton3.ShowActiveImage = true;
            this.bunifuImageButton3.ShowCursorChanges = true;
            this.bunifuImageButton3.ShowImageBorders = true;
            this.bunifuImageButton3.ShowSizeMarkers = false;
            this.bunifuImageButton3.Size = new System.Drawing.Size(87, 46);
            this.bunifuImageButton3.TabIndex = 73;
            this.bunifuImageButton3.ToolTipText = "";
            this.bunifuImageButton3.WaitOnLoad = false;
            this.bunifuImageButton3.Zoom = 40;
            this.bunifuImageButton3.ZoomSpeed = 10;
            // 
            // bunifuImageButton4
            // 
            this.bunifuImageButton4.ActiveImage = null;
            this.bunifuImageButton4.AllowAnimations = true;
            this.bunifuImageButton4.AllowBuffering = false;
            this.bunifuImageButton4.AllowToggling = false;
            this.bunifuImageButton4.AllowZooming = true;
            this.bunifuImageButton4.AllowZoomingOnFocus = false;
            this.bunifuImageButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton4.BackgroundImage")));
            this.bunifuImageButton4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton4.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton4.ErrorImage")));
            this.bunifuImageButton4.FadeWhenInactive = false;
            this.bunifuImageButton4.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton4.Image = null;
            this.bunifuImageButton4.ImageActive = null;
            this.bunifuImageButton4.ImageLocation = null;
            this.bunifuImageButton4.ImageMargin = 40;
            this.bunifuImageButton4.ImageSize = new System.Drawing.Size(47, 19);
            this.bunifuImageButton4.ImageZoomSize = new System.Drawing.Size(87, 59);
            this.bunifuImageButton4.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton4.InitialImage")));
            this.bunifuImageButton4.Location = new System.Drawing.Point(141, 398);
            this.bunifuImageButton4.Name = "bunifuImageButton4";
            this.bunifuImageButton4.Rotation = 0;
            this.bunifuImageButton4.ShowActiveImage = true;
            this.bunifuImageButton4.ShowCursorChanges = true;
            this.bunifuImageButton4.ShowImageBorders = true;
            this.bunifuImageButton4.ShowSizeMarkers = false;
            this.bunifuImageButton4.Size = new System.Drawing.Size(87, 59);
            this.bunifuImageButton4.TabIndex = 74;
            this.bunifuImageButton4.ToolTipText = "";
            this.bunifuImageButton4.WaitOnLoad = false;
            this.bunifuImageButton4.Zoom = 40;
            this.bunifuImageButton4.ZoomSpeed = 10;
            // 
            // bunifuImageButton5
            // 
            this.bunifuImageButton5.ActiveImage = null;
            this.bunifuImageButton5.AllowAnimations = true;
            this.bunifuImageButton5.AllowBuffering = false;
            this.bunifuImageButton5.AllowToggling = false;
            this.bunifuImageButton5.AllowZooming = true;
            this.bunifuImageButton5.AllowZoomingOnFocus = false;
            this.bunifuImageButton5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton5.BackgroundImage")));
            this.bunifuImageButton5.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton5.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton5.ErrorImage")));
            this.bunifuImageButton5.FadeWhenInactive = false;
            this.bunifuImageButton5.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton5.Image = null;
            this.bunifuImageButton5.ImageActive = null;
            this.bunifuImageButton5.ImageLocation = null;
            this.bunifuImageButton5.ImageMargin = 40;
            this.bunifuImageButton5.ImageSize = new System.Drawing.Size(47, 14);
            this.bunifuImageButton5.ImageZoomSize = new System.Drawing.Size(87, 54);
            this.bunifuImageButton5.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton5.InitialImage")));
            this.bunifuImageButton5.Location = new System.Drawing.Point(141, 463);
            this.bunifuImageButton5.Name = "bunifuImageButton5";
            this.bunifuImageButton5.Rotation = 0;
            this.bunifuImageButton5.ShowActiveImage = true;
            this.bunifuImageButton5.ShowCursorChanges = true;
            this.bunifuImageButton5.ShowImageBorders = true;
            this.bunifuImageButton5.ShowSizeMarkers = false;
            this.bunifuImageButton5.Size = new System.Drawing.Size(87, 54);
            this.bunifuImageButton5.TabIndex = 75;
            this.bunifuImageButton5.ToolTipText = "";
            this.bunifuImageButton5.WaitOnLoad = false;
            this.bunifuImageButton5.Zoom = 40;
            this.bunifuImageButton5.ZoomSpeed = 10;
            // 
            // bunifuImageButton6
            // 
            this.bunifuImageButton6.ActiveImage = null;
            this.bunifuImageButton6.AllowAnimations = true;
            this.bunifuImageButton6.AllowBuffering = false;
            this.bunifuImageButton6.AllowToggling = false;
            this.bunifuImageButton6.AllowZooming = true;
            this.bunifuImageButton6.AllowZoomingOnFocus = false;
            this.bunifuImageButton6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton6.BackgroundImage")));
            this.bunifuImageButton6.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton6.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton6.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton6.ErrorImage")));
            this.bunifuImageButton6.FadeWhenInactive = false;
            this.bunifuImageButton6.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton6.Image = null;
            this.bunifuImageButton6.ImageActive = null;
            this.bunifuImageButton6.ImageLocation = null;
            this.bunifuImageButton6.ImageMargin = 40;
            this.bunifuImageButton6.ImageSize = new System.Drawing.Size(47, 23);
            this.bunifuImageButton6.ImageZoomSize = new System.Drawing.Size(87, 63);
            this.bunifuImageButton6.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton6.InitialImage")));
            this.bunifuImageButton6.Location = new System.Drawing.Point(141, 523);
            this.bunifuImageButton6.Name = "bunifuImageButton6";
            this.bunifuImageButton6.Rotation = 0;
            this.bunifuImageButton6.ShowActiveImage = true;
            this.bunifuImageButton6.ShowCursorChanges = true;
            this.bunifuImageButton6.ShowImageBorders = true;
            this.bunifuImageButton6.ShowSizeMarkers = false;
            this.bunifuImageButton6.Size = new System.Drawing.Size(87, 63);
            this.bunifuImageButton6.TabIndex = 76;
            this.bunifuImageButton6.ToolTipText = "";
            this.bunifuImageButton6.WaitOnLoad = false;
            this.bunifuImageButton6.Zoom = 40;
            this.bunifuImageButton6.ZoomSpeed = 10;
            // 
            // bunifuImageButton7
            // 
            this.bunifuImageButton7.ActiveImage = null;
            this.bunifuImageButton7.AllowAnimations = true;
            this.bunifuImageButton7.AllowBuffering = false;
            this.bunifuImageButton7.AllowToggling = false;
            this.bunifuImageButton7.AllowZooming = true;
            this.bunifuImageButton7.AllowZoomingOnFocus = false;
            this.bunifuImageButton7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton7.BackgroundImage")));
            this.bunifuImageButton7.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuImageButton7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton7.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton7.ErrorImage")));
            this.bunifuImageButton7.FadeWhenInactive = false;
            this.bunifuImageButton7.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton7.Image = null;
            this.bunifuImageButton7.ImageActive = null;
            this.bunifuImageButton7.ImageLocation = null;
            this.bunifuImageButton7.ImageMargin = 40;
            this.bunifuImageButton7.ImageSize = new System.Drawing.Size(47, 20);
            this.bunifuImageButton7.ImageZoomSize = new System.Drawing.Size(87, 60);
            this.bunifuImageButton7.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton7.InitialImage")));
            this.bunifuImageButton7.Location = new System.Drawing.Point(141, 592);
            this.bunifuImageButton7.Name = "bunifuImageButton7";
            this.bunifuImageButton7.Rotation = 0;
            this.bunifuImageButton7.ShowActiveImage = true;
            this.bunifuImageButton7.ShowCursorChanges = true;
            this.bunifuImageButton7.ShowImageBorders = true;
            this.bunifuImageButton7.ShowSizeMarkers = false;
            this.bunifuImageButton7.Size = new System.Drawing.Size(87, 60);
            this.bunifuImageButton7.TabIndex = 77;
            this.bunifuImageButton7.ToolTipText = "";
            this.bunifuImageButton7.WaitOnLoad = false;
            this.bunifuImageButton7.Zoom = 40;
            this.bunifuImageButton7.ZoomSpeed = 10;
            // 
            // bt_thoat
            // 
            this.bt_thoat.BackColor = System.Drawing.Color.IndianRed;
            this.bt_thoat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt_thoat.BackgroundImage")));
            this.bt_thoat.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.tableLayoutPanel1.SetColumnSpan(this.bt_thoat, 2);
            this.bt_thoat.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.bt_thoat.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.125F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt_thoat.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bt_thoat.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bt_thoat.Location = new System.Drawing.Point(301, 659);
            this.bt_thoat.Margin = new System.Windows.Forms.Padding(4);
            this.bt_thoat.Name = "bt_thoat";
            this.bt_thoat.Size = new System.Drawing.Size(143, 69);
            this.bt_thoat.TabIndex = 63;
            this.bt_thoat.UseVisualStyleBackColor = false;
            this.bt_thoat.Click += new System.EventHandler(this.bt_thoat_Click);
            // 
            // txt_mk
            // 
            this.txt_mk.AcceptsReturn = false;
            this.txt_mk.AcceptsTab = false;
            this.txt_mk.AnimationSpeed = 200;
            this.txt_mk.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_mk.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_mk.BackColor = System.Drawing.Color.Transparent;
            this.txt_mk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_mk.BackgroundImage")));
            this.txt_mk.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_mk.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_mk.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_mk.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_mk.BorderRadius = 1;
            this.txt_mk.BorderThickness = 1;
            this.txt_mk.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_mk, 2);
            this.txt_mk.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_mk.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_mk.DefaultText = "";
            this.txt_mk.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_mk.Enabled = false;
            this.txt_mk.FillColor = System.Drawing.Color.White;
            this.txt_mk.HideSelection = true;
            this.txt_mk.IconLeft = null;
            this.txt_mk.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_mk.IconPadding = 10;
            this.txt_mk.IconRight = null;
            this.txt_mk.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_mk.Lines = new string[0];
            this.txt_mk.Location = new System.Drawing.Point(300, 592);
            this.txt_mk.MaxLength = 32767;
            this.txt_mk.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_mk.Modified = false;
            this.txt_mk.Multiline = false;
            this.txt_mk.Name = "txt_mk";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_mk.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_mk.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_mk.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_mk.OnIdleState = stateProperties4;
            this.txt_mk.Padding = new System.Windows.Forms.Padding(3);
            this.txt_mk.PasswordChar = '♥';
            this.txt_mk.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_mk.PlaceholderText = "Nhập mật khẩu";
            this.txt_mk.ReadOnly = false;
            this.txt_mk.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_mk.SelectedText = "";
            this.txt_mk.SelectionLength = 0;
            this.txt_mk.SelectionStart = 0;
            this.txt_mk.ShortcutsEnabled = true;
            this.txt_mk.Size = new System.Drawing.Size(346, 51);
            this.txt_mk.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_mk.TabIndex = 70;
            this.txt_mk.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_mk.TextMarginBottom = 0;
            this.txt_mk.TextMarginLeft = 3;
            this.txt_mk.TextMarginTop = 0;
            this.txt_mk.TextPlaceholder = "Nhập mật khẩu";
            this.txt_mk.UseSystemPasswordChar = false;
            this.txt_mk.WordWrap = true;
            // 
            // txt_chucvu
            // 
            this.txt_chucvu.AcceptsReturn = false;
            this.txt_chucvu.AcceptsTab = false;
            this.txt_chucvu.AnimationSpeed = 200;
            this.txt_chucvu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_chucvu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_chucvu.BackColor = System.Drawing.Color.Transparent;
            this.txt_chucvu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_chucvu.BackgroundImage")));
            this.txt_chucvu.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_chucvu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_chucvu.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_chucvu.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_chucvu.BorderRadius = 1;
            this.txt_chucvu.BorderThickness = 1;
            this.txt_chucvu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_chucvu, 2);
            this.txt_chucvu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_chucvu.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_chucvu.DefaultText = "";
            this.txt_chucvu.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_chucvu.Enabled = false;
            this.txt_chucvu.FillColor = System.Drawing.Color.White;
            this.txt_chucvu.HideSelection = true;
            this.txt_chucvu.IconLeft = null;
            this.txt_chucvu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_chucvu.IconPadding = 10;
            this.txt_chucvu.IconRight = null;
            this.txt_chucvu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_chucvu.Lines = new string[0];
            this.txt_chucvu.Location = new System.Drawing.Point(300, 463);
            this.txt_chucvu.MaxLength = 32767;
            this.txt_chucvu.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_chucvu.Modified = false;
            this.txt_chucvu.Multiline = false;
            this.txt_chucvu.Name = "txt_chucvu";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_chucvu.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_chucvu.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_chucvu.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_chucvu.OnIdleState = stateProperties8;
            this.txt_chucvu.Padding = new System.Windows.Forms.Padding(3);
            this.txt_chucvu.PasswordChar = '\0';
            this.txt_chucvu.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_chucvu.PlaceholderText = "♥";
            this.txt_chucvu.ReadOnly = false;
            this.txt_chucvu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_chucvu.SelectedText = "";
            this.txt_chucvu.SelectionLength = 0;
            this.txt_chucvu.SelectionStart = 0;
            this.txt_chucvu.ShortcutsEnabled = true;
            this.txt_chucvu.Size = new System.Drawing.Size(346, 52);
            this.txt_chucvu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_chucvu.TabIndex = 80;
            this.txt_chucvu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_chucvu.TextMarginBottom = 0;
            this.txt_chucvu.TextMarginLeft = 3;
            this.txt_chucvu.TextMarginTop = 0;
            this.txt_chucvu.TextPlaceholder = "♥";
            this.txt_chucvu.UseSystemPasswordChar = false;
            this.txt_chucvu.WordWrap = true;
            // 
            // txt_tk
            // 
            this.txt_tk.AcceptsReturn = false;
            this.txt_tk.AcceptsTab = false;
            this.txt_tk.AnimationSpeed = 200;
            this.txt_tk.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_tk.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_tk.BackColor = System.Drawing.Color.Transparent;
            this.txt_tk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_tk.BackgroundImage")));
            this.txt_tk.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_tk.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_tk.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_tk.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_tk.BorderRadius = 1;
            this.txt_tk.BorderThickness = 1;
            this.txt_tk.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_tk, 2);
            this.txt_tk.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_tk.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_tk.DefaultText = "";
            this.txt_tk.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_tk.Enabled = false;
            this.txt_tk.FillColor = System.Drawing.Color.White;
            this.txt_tk.HideSelection = true;
            this.txt_tk.IconLeft = null;
            this.txt_tk.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_tk.IconPadding = 10;
            this.txt_tk.IconRight = null;
            this.txt_tk.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_tk.Lines = new string[0];
            this.txt_tk.Location = new System.Drawing.Point(300, 523);
            this.txt_tk.MaxLength = 32767;
            this.txt_tk.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_tk.Modified = false;
            this.txt_tk.Multiline = false;
            this.txt_tk.Name = "txt_tk";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_tk.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_tk.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_tk.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_tk.OnIdleState = stateProperties12;
            this.txt_tk.Padding = new System.Windows.Forms.Padding(3);
            this.txt_tk.PasswordChar = '\0';
            this.txt_tk.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_tk.PlaceholderText = "♥";
            this.txt_tk.ReadOnly = false;
            this.txt_tk.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_tk.SelectedText = "";
            this.txt_tk.SelectionLength = 0;
            this.txt_tk.SelectionStart = 0;
            this.txt_tk.ShortcutsEnabled = true;
            this.txt_tk.Size = new System.Drawing.Size(346, 52);
            this.txt_tk.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_tk.TabIndex = 69;
            this.txt_tk.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_tk.TextMarginBottom = 0;
            this.txt_tk.TextMarginLeft = 3;
            this.txt_tk.TextMarginTop = 0;
            this.txt_tk.TextPlaceholder = "♥";
            this.txt_tk.UseSystemPasswordChar = false;
            this.txt_tk.WordWrap = true;
            // 
            // txt_sdt
            // 
            this.txt_sdt.AcceptsReturn = false;
            this.txt_sdt.AcceptsTab = false;
            this.txt_sdt.AnimationSpeed = 200;
            this.txt_sdt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_sdt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_sdt.BackColor = System.Drawing.Color.Transparent;
            this.txt_sdt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_sdt.BackgroundImage")));
            this.txt_sdt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_sdt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_sdt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_sdt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_sdt.BorderRadius = 1;
            this.txt_sdt.BorderThickness = 1;
            this.txt_sdt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_sdt, 2);
            this.txt_sdt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sdt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_sdt.DefaultText = "";
            this.txt_sdt.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_sdt.Enabled = false;
            this.txt_sdt.FillColor = System.Drawing.Color.White;
            this.txt_sdt.HideSelection = true;
            this.txt_sdt.IconLeft = null;
            this.txt_sdt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sdt.IconPadding = 10;
            this.txt_sdt.IconRight = null;
            this.txt_sdt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_sdt.Lines = new string[0];
            this.txt_sdt.Location = new System.Drawing.Point(300, 398);
            this.txt_sdt.MaxLength = 32767;
            this.txt_sdt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_sdt.Modified = false;
            this.txt_sdt.Multiline = false;
            this.txt_sdt.Name = "txt_sdt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sdt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_sdt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sdt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_sdt.OnIdleState = stateProperties16;
            this.txt_sdt.Padding = new System.Windows.Forms.Padding(3);
            this.txt_sdt.PasswordChar = '\0';
            this.txt_sdt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_sdt.PlaceholderText = "♥";
            this.txt_sdt.ReadOnly = false;
            this.txt_sdt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_sdt.SelectedText = "";
            this.txt_sdt.SelectionLength = 0;
            this.txt_sdt.SelectionStart = 0;
            this.txt_sdt.ShortcutsEnabled = true;
            this.txt_sdt.Size = new System.Drawing.Size(346, 46);
            this.txt_sdt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_sdt.TabIndex = 68;
            this.txt_sdt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_sdt.TextMarginBottom = 0;
            this.txt_sdt.TextMarginLeft = 3;
            this.txt_sdt.TextMarginTop = 0;
            this.txt_sdt.TextPlaceholder = "♥";
            this.txt_sdt.UseSystemPasswordChar = false;
            this.txt_sdt.WordWrap = true;
            // 
            // txt_gioitinh
            // 
            this.txt_gioitinh.AcceptsReturn = false;
            this.txt_gioitinh.AcceptsTab = false;
            this.txt_gioitinh.AnimationSpeed = 200;
            this.txt_gioitinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_gioitinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_gioitinh.BackColor = System.Drawing.Color.Transparent;
            this.txt_gioitinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_gioitinh.BackgroundImage")));
            this.txt_gioitinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_gioitinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_gioitinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_gioitinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_gioitinh.BorderRadius = 1;
            this.txt_gioitinh.BorderThickness = 1;
            this.txt_gioitinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_gioitinh, 2);
            this.txt_gioitinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_gioitinh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_gioitinh.DefaultText = "";
            this.txt_gioitinh.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_gioitinh.Enabled = false;
            this.txt_gioitinh.FillColor = System.Drawing.Color.White;
            this.txt_gioitinh.HideSelection = true;
            this.txt_gioitinh.IconLeft = null;
            this.txt_gioitinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_gioitinh.IconPadding = 10;
            this.txt_gioitinh.IconRight = null;
            this.txt_gioitinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_gioitinh.Lines = new string[0];
            this.txt_gioitinh.Location = new System.Drawing.Point(300, 346);
            this.txt_gioitinh.MaxLength = 32767;
            this.txt_gioitinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_gioitinh.Modified = false;
            this.txt_gioitinh.Multiline = false;
            this.txt_gioitinh.Name = "txt_gioitinh";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_gioitinh.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_gioitinh.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_gioitinh.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_gioitinh.OnIdleState = stateProperties20;
            this.txt_gioitinh.Padding = new System.Windows.Forms.Padding(3);
            this.txt_gioitinh.PasswordChar = '\0';
            this.txt_gioitinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_gioitinh.PlaceholderText = "♥";
            this.txt_gioitinh.ReadOnly = false;
            this.txt_gioitinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_gioitinh.SelectedText = "";
            this.txt_gioitinh.SelectionLength = 0;
            this.txt_gioitinh.SelectionStart = 0;
            this.txt_gioitinh.ShortcutsEnabled = true;
            this.txt_gioitinh.Size = new System.Drawing.Size(346, 46);
            this.txt_gioitinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_gioitinh.TabIndex = 79;
            this.txt_gioitinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_gioitinh.TextMarginBottom = 0;
            this.txt_gioitinh.TextMarginLeft = 3;
            this.txt_gioitinh.TextMarginTop = 0;
            this.txt_gioitinh.TextPlaceholder = "♥";
            this.txt_gioitinh.UseSystemPasswordChar = false;
            this.txt_gioitinh.WordWrap = true;
            // 
            // txt_ten
            // 
            this.txt_ten.AcceptsReturn = false;
            this.txt_ten.AcceptsTab = false;
            this.txt_ten.AnimationSpeed = 200;
            this.txt_ten.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ten.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ten.BackColor = System.Drawing.Color.Transparent;
            this.txt_ten.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ten.BackgroundImage")));
            this.txt_ten.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ten.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ten.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_ten.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ten.BorderRadius = 1;
            this.txt_ten.BorderThickness = 1;
            this.txt_ten.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_ten, 2);
            this.txt_ten.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ten.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ten.DefaultText = "";
            this.txt_ten.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_ten.Enabled = false;
            this.txt_ten.FillColor = System.Drawing.Color.White;
            this.txt_ten.HideSelection = true;
            this.txt_ten.IconLeft = null;
            this.txt_ten.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ten.IconPadding = 10;
            this.txt_ten.IconRight = null;
            this.txt_ten.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ten.Lines = new string[0];
            this.txt_ten.Location = new System.Drawing.Point(300, 275);
            this.txt_ten.MaxLength = 32767;
            this.txt_ten.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ten.Modified = false;
            this.txt_ten.Multiline = false;
            this.txt_ten.Name = "txt_ten";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ten.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ten.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ten.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ten.OnIdleState = stateProperties24;
            this.txt_ten.Padding = new System.Windows.Forms.Padding(3);
            this.txt_ten.PasswordChar = '\0';
            this.txt_ten.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ten.PlaceholderText = "♥";
            this.txt_ten.ReadOnly = false;
            this.txt_ten.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ten.SelectedText = "";
            this.txt_ten.SelectionLength = 0;
            this.txt_ten.SelectionStart = 0;
            this.txt_ten.ShortcutsEnabled = true;
            this.txt_ten.Size = new System.Drawing.Size(346, 52);
            this.txt_ten.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ten.TabIndex = 66;
            this.txt_ten.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ten.TextMarginBottom = 0;
            this.txt_ten.TextMarginLeft = 3;
            this.txt_ten.TextMarginTop = 0;
            this.txt_ten.TextPlaceholder = "♥";
            this.txt_ten.UseSystemPasswordChar = false;
            this.txt_ten.WordWrap = true;
            // 
            // txt_ma
            // 
            this.txt_ma.AcceptsReturn = false;
            this.txt_ma.AcceptsTab = false;
            this.txt_ma.AnimationSpeed = 200;
            this.txt_ma.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ma.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ma.BackColor = System.Drawing.Color.Transparent;
            this.txt_ma.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ma.BackgroundImage")));
            this.txt_ma.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ma.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ma.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.txt_ma.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ma.BorderRadius = 1;
            this.txt_ma.BorderThickness = 1;
            this.txt_ma.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tableLayoutPanel1.SetColumnSpan(this.txt_ma, 2);
            this.txt_ma.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ma.DefaultText = "";
            this.txt_ma.Dock = System.Windows.Forms.DockStyle.Top;
            this.txt_ma.Enabled = false;
            this.txt_ma.FillColor = System.Drawing.Color.White;
            this.txt_ma.HideSelection = true;
            this.txt_ma.IconLeft = null;
            this.txt_ma.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.IconPadding = 10;
            this.txt_ma.IconRight = null;
            this.txt_ma.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ma.Lines = new string[0];
            this.txt_ma.Location = new System.Drawing.Point(300, 206);
            this.txt_ma.MaxLength = 32767;
            this.txt_ma.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ma.Modified = false;
            this.txt_ma.Multiline = false;
            this.txt_ma.Name = "txt_ma";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ma.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ma.OnIdleState = stateProperties28;
            this.txt_ma.Padding = new System.Windows.Forms.Padding(3);
            this.txt_ma.PasswordChar = '\0';
            this.txt_ma.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ma.PlaceholderText = "♥";
            this.txt_ma.ReadOnly = false;
            this.txt_ma.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ma.SelectedText = "";
            this.txt_ma.SelectionLength = 0;
            this.txt_ma.SelectionStart = 0;
            this.txt_ma.ShortcutsEnabled = true;
            this.txt_ma.Size = new System.Drawing.Size(346, 52);
            this.txt_ma.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ma.TabIndex = 82;
            this.txt_ma.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ma.TextMarginBottom = 0;
            this.txt_ma.TextMarginLeft = 3;
            this.txt_ma.TextMarginTop = 0;
            this.txt_ma.TextPlaceholder = "♥";
            this.txt_ma.UseSystemPasswordChar = false;
            this.txt_ma.WordWrap = true;
            // 
            // hanh
            // 
            this.tableLayoutPanel1.SetColumnSpan(this.hanh, 2);
            this.hanh.Location = new System.Drawing.Point(3, 3);
            this.hanh.Name = "hanh";
            this.hanh.Size = new System.Drawing.Size(177, 197);
            this.hanh.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.hanh.TabIndex = 83;
            this.hanh.TabStop = false;
            // 
            // ThongTin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(826, 732);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "ThongTin";
            this.Text = "THÔNG TIN";
            this.Load += new System.EventHandler(this.ThongTin_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.hanh)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ten;
        private Bunifu.UI.WinForms.BunifuTextBox txt_sdt;
        private Bunifu.UI.WinForms.BunifuTextBox txt_tk;
        private Bunifu.UI.WinForms.BunifuTextBox txt_mk;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton3;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton4;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton5;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton6;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton7;
        private System.Windows.Forms.Button bt_thoat;
        private Bunifu.UI.WinForms.BunifuTextBox txt_gioitinh;
        private Bunifu.UI.WinForms.BunifuTextBox txt_chucvu;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ma;
        private System.Windows.Forms.PictureBox hanh;
    }
}